export default {
  RECEIVE_CURRENCIES_SUCCESS: 'RECEIVE_CURRENCIES_SUCCESS',
  RECEIVE_RATES_SUCCESS: 'RECEIVE_RATES_SUCCESS',
  SET_CURRENCIES: 'SET_CURRENCIES',
  HAS_FEW_CURRENCIES: 'HAS_FEW_CURRENCIES',
  UPDATE_INPUT: 'UPDATE_INPUT',
  UPDATE_OUTPUT: 'UPDATE_OUTPUT',
  TOGGLE_FROM_DROPDOWN: 'TOGGLE_FROM_DROPDOWN',
  TOGGLE_TO_DROPDOWN: 'TOGGLE_TO_DROPDOWN',
  CHANGE_FROM_CURRENCY: 'CHANGE_FROM_CURRENCY',
  CHANGE_TO_CURRENCY: 'CHANGE_TO_CURRENCY',
  EXCHANGE_REQUEST: 'EXCHANGE_REQUEST',
  EXCHANGE_SUCCESS: 'EXCHANGE_SUCCESS',
  EXCHANGE_ERROR: 'EXCHANGE_ERROR'
};
