export default {
  RECEIVE_CURRENCIES_SUCCESS: 'RECEIVE_CURRENCIES_SUCCESS',
  RECEIVE_RATES_SUCCESS: 'RECEIVE_RATES_SUCCESS',
  SET_CURRENCIES: 'SET_CURRENCIES',
  HAS_FEW_CURRENCIES: 'HAS_FEW_CURRENCIES',
  UPDATE_INPUT: 'UPDATE_INPUT',
  UPDATE_OUTPUT: 'UPDATE_OUTPUT',
  SHOW_BASE_DROPDOWN: 'SHOW_BASE_DROPDOWN',
  SHOW_QUOTE_DROPDOWN: 'SHOW_QUOTE_DROPDOWN',
  HIDE_DROPDOWN: 'HIDE_DROPDOWN',
  CHANGE_BASE_CURRENCY: 'CHANGE_BASE_CURRENCY',
  CHANGE_QUOTE_CURRENCY: 'CHANGE_QUOTE_CURRENCY',
  UPDATE_WARNING: 'UPDATE_WARNING',
  EXCHANGE_REQUEST: 'EXCHANGE_REQUEST',
  EXCHANGE_SUCCESS: 'EXCHANGE_SUCCESS',
  EXCHANGE_ERROR: 'EXCHANGE_ERROR'
};
